# Generated by Django 2.1.5 on 2019-03-07 20:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FullStackApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributevalue',
            old_name='attribute_id',
            new_name='attribute',
        ),
        migrations.RenameField(
            model_name='audit',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='shipping_region_id',
            new_name='shipping_region',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='shipping_id',
            new_name='shipping',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='tax_id',
            new_name='tax',
        ),
        migrations.RenameField(
            model_name='productattribute',
            old_name='attribute_value_id',
            new_name='attribute_value',
        ),
        migrations.RenameField(
            model_name='productattribute',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='reviewtable',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='reviewtable',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='product_id',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(default=1, on_delete='order_detail_related_product', to='FullStackApp.Product'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together={('product', 'attribute_value')},
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('product', 'category')},
        ),
    ]
