# Generated by Django 2.1.5 on 2019-03-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FullStackApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(upload_to=''),
        ),
    ]
