# Generated by Django 2.1.5 on 2019-03-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FullStackApp', '0002_auto_20190310_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=101),
        ),
    ]
