# Generated by Django 2.1.5 on 2019-03-07 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FullStackApp', '0002_auto_20190307_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='cart',
            new_name='cart_id',
        ),
    ]
