# Generated by Django 2.1.5 on 2019-03-08 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FullStackApp', '0003_auto_20190307_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='id',
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='related_product', serialize=False, to='FullStackApp.Product'),
        ),
    ]
