# Generated by Django 2.1.5 on 2019-03-08 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FullStackApp', '0004_auto_20190308_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_product', to='FullStackApp.Product'),
        ),
    ]
