# Generated by Django 2.1.5 on 2019-03-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FullStackApp', '0005_auto_20190308_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='name',
            field=models.CharField(default=-1, max_length=100),
            preserve_default=False,
        ),
    ]
