# Generated by Django 2.1.7 on 2019-03-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FullStackApp', '0005_auto_20190318_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='shipping_type',
            field=models.CharField(max_length=100),
        ),
    ]
