# Generated by Django 2.1.5 on 2019-03-08 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FullStackApp', '0006_attributevalue_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributevalue',
            name='name',
        ),
    ]
