# Generated by Django 2.1.7 on 2019-03-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FullStackApp', '0007_auto_20190320_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
    ]
