# Generated by Django 2.1.5 on 2019-03-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FullStackApp', '0007_remove_attributevalue_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='shipping_region_id',
            new_name='shipping_region',
        ),
    ]
