# Generated by Django 2.1.7 on 2019-03-31 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FullStackApp', '0008_orders_has_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name_plural': 'orders'},
        ),
    ]
